spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.ftt.forum.entity

#showSql
logging:
  level:
    com:
      ftt:
        forum:
          mapper: debug

server:
  port: 8080

